site_name: 注文受付システム (OrderTaking) - 関数型ドメイン駆動設計ケーススタディ
site_description: F#の関数型プログラミングとドメイン駆動設計による注文受付システムの実装ガイド
site_author: Project Team
repo_url: https://github.com/k2works/case-study-functional-ddd
repo_name: case-study-functional-ddd

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight

extra_css:
  - docs/mkdocs/assets/css/extra.css

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: plantuml
          class: plantuml
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.emoji
  - admonition
  - toc:
      permalink: true
  - plantuml_markdown:
      server: !!python/object/apply:os.getenv
        - PLANTUML_SERVER_URL
        - http://www.plantuml.com/plantuml
      format: svg

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@10.6.1/dist/mermaid.min.js
  - docs/assets/js/extra.js

extra:
  plantuml_url: http://www.plantuml.com/plantuml
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/k2works
      name: GitHub Repository/claude-code-booster

plugins:
  - search

nav:
  - ホーム: index.md
  - 要件定義:
    - 要件定義: requirements/requirements_definition.md
    - ビジネスユースケース: requirements/business_usecase.md
    - システムユースケース: requirements/system_usecase.md
    - ユーザーストーリー: requirements/user_story.md
  - 設計:
    - アーキテクチャ設計: design/architecture.md
    - ドメインモデル設計: design/domain_model.md
    - データモデル設計: design/data-model.md
    - 技術スタック: design/tech_stack.md
    - テスト戦略: design/test_strategy.md
  - 実装ガイド:
    - F# アプリケーション環境構築ガイド: reference/F#アプリケーション環境構築ガイド.md
    - F# API構築ガイド: reference/F#API構築ガイド.md
    - UI設計ガイド: reference/UI設計ガイド.md
    - アーキテクチャ設計ガイド: reference/アーキテクチャ設計ガイド.md
    - インフラ設計ガイド: reference/インフラ設計ガイド.md
    - テスト戦略ガイド: reference/テスト戦略ガイド.md
  - F# 学習教材:
    - F# TDD入門 第1部: reference/テスト駆動開発から始めるFSharp入門1.md
    - F# TDD入門 第2部: reference/テスト駆動開発から始めるFSharp入門2.md
    - F# TDD入門 第3部: reference/テスト駆動開発から始めるFSharp入門3.md
    - F# TDD入門 第4部: reference/テスト駆動開発から始めるFSharp入門4.md
  - 開発理念:
    - よいソフトウェアとは: reference/よいソフトウェアとは.md
    - エクストリームプログラミング: reference/エクストリームプログラミング.md
